actions:
  1:
    action: delete_indices
    description: >-
       Delete the oldest indices with sessions2- prefixes when their cumulative
       disk consumtion is greater than ${CURATOR_DELETE_GIGS:1000000} gigabytes. Ignore
       the error if the filter does not result in an actionable list of indices
       (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: sessions2-
      exclude:
    - filtertype: space
      disk_space: ${CURATOR_DELETE_GIGS:1000000}
      use_age: True
      source: name
      timestring: '%y%m%d'
      exclude:
  2:
    action: delete_indices
    description: >-
       Delete indices older than ${CURATOR_DELETE_COUNT:99} ${CURATOR_DELETE_UNITS:years}
       (based on index name), for sessions2-prefixed indices. Ignore the error if the
       filter does not result in an actionable list of indices (ignore_empty_list) and
       exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: sessions2-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%y%m%d'
      unit: ${CURATOR_DELETE_UNITS:years}
      unit_count: ${CURATOR_DELETE_COUNT:99}
      exclude:
  3:
    action: close
    description: >-
       Close indices older than ${CURATOR_CLOSE_COUNT:5} ${CURATOR_CLOSE_UNITS:years}
       (based on index name), for sessions2-prefixed indices, to conserve memory.
       Ignore the error if the filter does not result in an actionable list of indices
       (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: sessions2-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%y%m%d'
      unit: ${CURATOR_CLOSE_UNITS:years}
      unit_count: ${CURATOR_CLOSE_COUNT:5}
      exclude: