repository: mmguero-dev/Malcolm
title: Malcolm
description: A powerful, easily deployable network traffic analysis tool suite
logo: docs/images/logo/Malcolm_outline_banner_dark.png
remote_theme: pages-themes/minimal@v0.2.0
external_download_url: https://malcolm.fyi/download/
youtube_url: https://www.youtube.com/c/MalcolmNetworkTrafficAnalysisToolSuite
docs_uri: docs/
alerting_docs_uri: docs/alerting.html
anomaly_detection_docs_uri: docs/anomaly-detection.html
api_docs_uri: docs/api.html
arkime_docs_uri: docs/arkime.html
components_docs_uri: docs/components.html
configuring_docs_uri: docs/malcolm-preparation.html
contributing_docs_uri: docs/contributing-guide.html
dashboards_docs_uri: docs/dashboards.html
hardening_docs_uri: docs/hardening.html
hedgehog_docs_uri: docs/hedgehog.html
live_analysis_docs_uri: docs/live-analysis.html
protocols_docs_uri: docs/protocols.html
queries_docs_uri: docs/queries-cheat-sheet.html
quickstart_docs_uri: docs/quickstart.html
severity_docs_uri: docs/severity.html
thirdparty_logs_docs_uri: docs/third-party-logs.html
upload_docs_uri: docs/upload.html
github:
  owner_name: Seth Grover
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
show_downloads: true
relative_links:
  enabled: true
  collections: true
exclude:
  - api
  - arkime
  - arkime-logs
  - arkime-raw
  - auth.env
  - cidr-map.txt
  - dashboards
  - docker-compose-standalone.yml
  - docker-compose.yml
  - docs/images/hedgehog/logo/font
  - docs/images/font
  - docs/quick-start
  - docs/slides
  - docs/stix
  - docs/web
  - Dockerfiles
  - .dockerignore
  - .envrc
  - filebeat
  - file-monitor
  - file-upload
  - freq-server
  - .git
  - .github
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - host-map.txt
  - htadmin
  - .ldap_config_defaults
  - logstash
  - malcolm-iso
  - name-map-ui
  - netbox
  - net-map.json
  - nginx
  - opensearch
  - opensearch-backup
  - .opensearch.primary.curlrc
  - .opensearch.secondary.curlrc
  - pcap
  - pcap-capture
  - pcap-monitor
  - scripts
  - sensor-iso
  - shared
  - suricata
  - suricata-logs
  - .tmp
  - .travis.yml
  - .trigger_workflow_build
  - yara
  - zeek
  - zeek-logs
