metricbeat.config.modules:
  path: ${path.config}/conf.d/*.yml
  reload.period: 10s
  reload.enabled: false

metricbeat.max_start_delay: 10s

#==========================  Modules configuration ============================
metricbeat.modules:

#------------------------------- System Module -------------------------------
- module: system
  period: ${BEAT_INTERVAL}
  metricsets:
    - cpu             # CPU usage
    - load            # CPU load averages
    - memory          # Memory usage
    - network         # Network IO
    - process         # Per process metrics
    - process_summary # Process summary
    - uptime          # System Uptime
    - diskio          # Disk IO
  enabled: true
  processes: ['.*']
  process.include_top_n:
    enabled: true
    by_cpu: 10
    by_memory: 10

  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]

- module: system
  period: 1m
  metricsets:
    - filesystem     # File system usage for each mountpoint
    - fsstat         # File system summary metrics
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib|boot)($|/)'

#================================ General ======================================
fields_under_root: true

processors:
  - add_tags:
      tags: [_malcolm_beats]

#================================ Outputs ======================================

#-------------------------- Logstash Output ------------------------------------
output.logstash:
  hosts: ["${BEAT_LS_HOST}:${BEAT_LS_PORT}"]
  ssl.enabled: ${BEAT_LS_SSL:false}
  ssl.certificate_authorities: ["${BEAT_LS_SSL_CA_CRT}"]
  ssl.certificate: "${BEAT_LS_SSL_CLIENT_CRT}"
  ssl.key: "${BEAT_LS_SSL_CLIENT_KEY}"
  ssl.supported_protocols: "TLSv1.2"
  ssl.verification_mode: "${BEAT_LS_SSL_VERIFY}"

#================================ Logging ======================================
logging.metrics.enabled: false
