protologbeat:
  address: "127.0.0.1"
  port: 9515
  protocol: udp
  json_mode: true
  merge_fields_to_root: true
  max_msg_size: 8192
  default_es_log_type: protologbeat

#================================ General ======================================
fields_under_root: true

processors:
  - add_tags:
      tags: [_malcolm_beats, _malcolm_heatbeat]

#================================ Outputs ======================================

#-------------------------- Logstash Output ------------------------------------
output.logstash:
  hosts: ["${BEAT_LS_HOST}:${BEAT_LS_PORT}"]
  ssl.enabled: ${BEAT_LS_SSL:false}
  ssl.certificate_authorities: ["${BEAT_LS_SSL_CA_CRT}"]
  ssl.certificate: "${BEAT_LS_SSL_CLIENT_CRT}"
  ssl.key: "${BEAT_LS_SSL_CLIENT_KEY}"
  ssl.supported_protocols: "TLSv1.2"
  ssl.verification_mode: "${BEAT_LS_SSL_VERIFY}"

#================================ Logging ======================================
logging.metrics.enabled: false
