---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: malcolm
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-proxy
            port:
              number: 443

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: malcolm
spec:
  ports:
    - port: 443
      protocol: TCP
  selector:
    app: malcolm-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: malcolm-app
  namespace: malcolm
spec:
  selector:
    matchLabels:
      app: malcolm-app
  replicas: 1
  template:
    metadata:
      labels:
        app: malcolm-app
    spec:
      containers:
      - name: nginx-proxy-container
        image: ghcr.io/idaholab/malcolmnetsec/nginx-proxy:kubernetes
        imagePullPolicy: Always
        ports:
          - containerPort: 443
        env:
          - name: PUID
            value: '1000'
          - name: PGID
            value: '1000'
          - name: PUSER_CA_TRUST
            value: '/var/local/ca-trust'
          - name: NGINX_BASIC_AUTH
            value: 'true'
          - name: NGINX_LDAP_TLS_STUNNEL
            value: 'false'
          - name: NGINX_LDAP_TLS_STUNNEL_CHECK_HOST
            value: ''
          - name: NGINX_LDAP_TLS_STUNNEL_CHECK_IP
            value: ''
          - name: NGINX_LDAP_TLS_STUNNEL_VERIFY_LEVEL
            value: '2'
          - name: NGINX_SSL
            value: 'true'
          - name: NGINX_LOG_ACCESS_AND_ERRORS
            value: 'false'
          - name: CONFIG_MAP_DIR
            value: 'configmap'
        livenessProbe:
          exec:
            command:
            - curl
            - --insecure
            - --silent
            - https://localhost:443
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: etc-nginx-volume
          mountPath: /etc/nginx/configmap
        - name: var-local-catrust-volume
          mountPath: /var/local/ca-trust/configmap
        - name: etc-nginx-certs-volume
          mountPath: /etc/nginx/certs/configmap
        - name: etc-nginx-certs-pem-volume
          mountPath: /etc/nginx/dhparam/configmap
      volumes:
      - name: etc-nginx-volume
        configMap:
          name: etc-nginx
      - name: var-local-catrust-volume
        configMap:
          name: var-local-catrust
      - name: etc-nginx-certs-volume
        configMap:
          name: etc-nginx-certs
      - name: etc-nginx-certs-pem-volume
        configMap:
          name: etc-nginx-certs-pem