---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: malcolm
spec:
  ports:
    - port: 9200
      protocol: TCP
  selector:
    name: opensearch-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: opensearch-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: opensearch-deployment
    spec:
      containers:
      - name: opensearch-container
        image: ghcr.io/idaholab/malcolm/opensearch:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        ports:
          - containerPort: 9200
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: opensearch-env
        env:
          - name: OPENSEARCH_DISABLED
            value: "true"
          - name: VIRTUAL_HOST
            value: "os.malcolm.local"
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: opensearch-var-local-catrust-volume
          - mountPath: /var/local/curlrc/configmap
            name: opensearch-opensearch-curlrc-volume
          - mountPath: "/usr/share/opensearch/data"
            name: opensearch-data-volume
          - mountPath: "/opt/opensearch/backup"
            name: opensearch-backup-volume
      volumes:
        - name: opensearch-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: opensearch-opensearch-curlrc-volume
          configMap:
            name: opensearch-curlrc
        - name: opensearch-data-volume
          persistentVolumeClaim:
            claimName: opensearch-claim
        - name: opensearch-backup-volume
          persistentVolumeClaim:
            claimName: opensearch-backup-claim
