---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: malcolm
spec:
  ports:
    - port: 9200
      protocol: TCP
  selector:
    name: opensearch-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: opensearch-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: opensearch-deployment
    spec:
      containers:
      - name: opensearch-container
        image: ghcr.io/idaholab/malcolm/opensearch:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - containerPort: 9200
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: opensearch-env
        env:
          - name: OPENSEARCH_DISABLED
            value: "true"
          - name: VIRTUAL_HOST
            value: "os.malcolm.local"
