---
apiVersion: v1
kind: Service
metadata:
  name: upload
  namespace: malcolm
spec:
  ports:
    - port: 22
      protocol: TCP
      name: ssh
    - port: 80
      protocol: TCP
      name: http
  selector:
    name: upload-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: upload-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: upload-deployment
    spec:
      containers:
      - name: upload-container
        image: ghcr.io/idaholab/malcolm/file-upload:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - containerPort: 22
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
        env:
          - name: UPLOAD_DISABLED
            value: "true"