---
apiVersion: v1
kind: Service
metadata:
  name: pcapmon
  namespace: malcolm
spec:
  ports:
    - port: 30441
      protocol: TCP
  selector:
    name: pcap-monitor-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcap-monitor-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: pcap-monitor-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: pcap-monitor-deployment
    spec:
      containers:
      - name: pcap-monitor-container
        image: ghcr.io/idaholab/malcolm/pcap-monitor:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - containerPort: 30441
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: opensearch-env
          - configMapRef:
              name: upload-common-env
        livenessProbe:
          exec:
            command:
            - supervisorctl
            - status
            - watch-upload
            - pcap-publisher
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: pcapmon-var-local-catrust-volume
          - mountPath: /var/local/curlrc/configmap
            name: pcapmon-opensearch-curlrc-volume
          - mountPath: "/pcap"
            name: pcapmon-pcap-volume
          - mountPath: "/zeek"
            name: pcapmon-zeek-volume
      volumes:
        - name: pcapmon-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: pcapmon-opensearch-curlrc-volume
          configMap:
            name: opensearch-curlrc
        - name: pcapmon-pcap-volume
          persistentVolumeClaim:
            claimName: pcap-claim
        - name: pcapmon-zeek-volume
          persistentVolumeClaim:
            claimName: zeek-claim