---
apiVersion: v1
kind: Service
metadata:
  name: arkime
  namespace: malcolm
spec:
  ports:
    - port: 8005
      protocol: TCP
  selector:
    name: arkime-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arkime-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: arkime-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: arkime-deployment
    spec:
      containers:
      - name: arkime-container
        image: ghcr.io/idaholab/malcolm/arkime:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - containerPort: 8005
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: opensearch-env
          - configMapRef:
              name: common-upload-env
          - configMapRef:
              name: arkime-env
        env:
          - name: ARKIME_DISABLED
            value: "true"
          - name: VIRTUAL_HOST
            value: "arkime.malcolm.local"