---
apiVersion: v1
kind: Service
metadata:
  name: arkime
  namespace: malcolm
spec:
  ports:
    - port: 8005
      protocol: TCP
  selector:
    name: arkime-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arkime-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: arkime-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: arkime-deployment
    spec:
      containers:
      - name: arkime-container
        image: ghcr.io/idaholab/malcolm/arkime:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - containerPort: 8005
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: opensearch-env
          - configMapRef:
              name: auth-env
          - configMapRef:
              name: upload-common-env
          - configMapRef:
              name: arkime-env
        env:
          - name: VIRTUAL_HOST
            value: "arkime.malcolm.local"
        livenessProbe:
          exec:
            command:
            - curl
            - --insecure
            - --silent
            - --fail
            - https://localhost:8005/_ns_/nstest.html
          initialDelaySeconds: 210
          periodSeconds: 90
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: arkime-var-local-catrust-volume
          - mountPath: /var/local/curlrc/configmap
            name: arkime-opensearch-curlrc-volume
          - mountPath: "/data/pcap"
            name: arkime-pcap-volume
      volumes:
        - name: arkime-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: arkime-opensearch-curlrc-volume
          configMap:
            name: opensearch-curlrc
        - name: arkime-pcap-volume
          persistentVolumeClaim:
            claimName: pcap-claim
