---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: malcolm
spec:
  ports:
    - port: 5000
      protocol: TCP
  selector:
    name: api-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: api-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: api-deployment
    spec:
      containers:
      - name: api-container
        image: ghcr.io/idaholab/malcolm/api:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - containerPort: 5000
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: opensearch-env
        env:
          - name: API_DISABLED
            value: "true"
          - name: VIRTUAL_HOST
            value: "api.malcolm.local"