---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suricata-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: suricata-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: suricata-deployment
    spec:
      containers:
      - name: suricata-container
        image: ghcr.io/idaholab/malcolm/suricata:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: upload-common-env
          - configMapRef:
              name: suricata-env
          - configMapRef:
              name: suricata-offline-env
        env:
          - name: SURICATA_DISABLED
            value: "true"
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: suricata-var-local-catrust-volume
          - mountPath: "/data/pcap"
            name: suricata-pcap-volume
      volumes:
        - name: suricata-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: suricata-pcap-volume
          persistentVolumeClaim:
            claimName: pcap-claim
