---
apiVersion: v1
kind: Service
metadata:
  name: file-monitor
  namespace: malcolm
spec:
  ports:
    - port: 3310
      protocol: TCP
  selector:
    name: file-monitor-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-monitor-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: file-monitor-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: file-monitor-deployment
    spec:
      containers:
      - name: file-monitor-container
        image: ghcr.io/idaholab/malcolm/file-monitor:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - containerPort: 3310
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: zeek-env
        env:
          - name: FILE_MONITOR_DISABLED
            value: "true"
          - name: VIRTUAL_HOST
            value: "file-monitor.malcolm.local"
