---
apiVersion: v1
kind: Service
metadata:
  name: filebeat
  namespace: malcolm
spec:
  ports:
    - port: 5045
      protocol: TCP
  selector:
    name: filebeat-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: filebeat-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: filebeat-deployment
    spec:
      containers:
      - name: filebeat-container
        image: ghcr.io/idaholab/malcolm/filebeat-oss:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - containerPort: 5045
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: nginx-env
          - configMapRef:
              name: opensearch-env
          - configMapRef:
              name: filebeat-env
          - configMapRef:
              name: upload-common-env
          - configMapRef:
              name: beats-common-env
        env:
          - name: FILEBEAT_DISABLED
            value: "true"
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: filebeat-var-local-catrust-volume
          - mountPath: /var/local/curlrc/configmap
            name: filebeat-opensearch-curlrc-volume
          - mountPath: /certs/configmap
            name: filebeat-certs-volume
      volumes:
        - name: filebeat-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: filebeat-opensearch-curlrc-volume
          configMap:
            name: opensearch-curlrc
        - name: filebeat-certs-volume
          configMap:
            name: filebeat-certs
