---
apiVersion: v1
kind: Service
metadata:
  name: filebeat
  namespace: malcolm
spec:
  ports:
    - port: 5045
      protocol: TCP
  selector:
    name: filebeat-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: filebeat-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: filebeat-deployment
    spec:
      containers:
      - name: filebeat-container
        image: ghcr.io/idaholab/malcolm/filebeat-oss:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - containerPort: 5045
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: nginx-env
          - configMapRef:
              name: opensearch-env
          - configMapRef:
              name: filebeat-env
          - configMapRef:
              name: common-upload-env
          - configMapRef:
              name: common-beats-env
        env:
          - name: FILEBEAT_DISABLED
            value: "true"