---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: malcolm
spec:
  ports:
    - port: 5044
      protocol: TCP
      name: lumberjack
    - port: 9600
      protocol: TCP
      name: api
  selector:
    name: logstash-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: logstash-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: logstash-deployment
    spec:
      containers:
      - name: logstash-container
        image: ghcr.io/idaholab/malcolm/logstash-oss:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - containerPort: 5044
          - containerPort: 9600
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: opensearch-env
          - configMapRef:
              name: netbox-env
          - configMapRef:
              name: logstash-env
          - configMapRef:
              name: common-beats-env
          - configMapRef:
              name: common-lookup-env
        env:
          - name: LOGSTASH_DISABLED
            value: "true"
