---
apiVersion: v1
kind: Service
metadata:
  name: netbox-redis
  namespace: malcolm
spec:
  ports:
    - port: 6379
      protocol: TCP
  selector:
    name: netbox-redis-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox-redis-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: netbox-redis-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: netbox-redis-deployment
    spec:
      containers:
      - name: netbox-redis-container
        image: ghcr.io/idaholab/malcolm/redis:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - containerPort: 6379
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: netbox-env
        env:
          - name: NETBOX_REDIS_DISABLED
            value: "true"
          - name: VIRTUAL_HOST
            value: "netbox-redis.malcolm.local"