---
apiVersion: v1
kind: Service
metadata:
  name: netbox
  namespace: malcolm
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: eightyeighty
    - port: 8081
      protocol: TCP
      name: eightyeightyone
    - port: 9001
      protocol: TCP
      name: ninethousandone
  selector:
    name: netbox-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: netbox-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: netbox-deployment
    spec:
      containers:
      - name: netbox-container
        image: ghcr.io/idaholab/malcolm/netbox:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - containerPort: 8080
          - containerPort: 8081
          - containerPort: 9001
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: netbox-env
          - configMapRef:
              name: netbox-netbox-env
        env:
          - name: VIRTUAL_HOST
            value: "netbox.malcolm.local"
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: netbox-var-local-catrust-volume
          - mountPath: /usr/local/share/configmap
            name: netbox-netmap-json-volume
      volumes:
        - name: netbox-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: netbox-netmap-json-volume
          configMap:
            name: netbox-netmap-json
