---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeek-live-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: zeek-live-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: zeek-live-deployment
    spec:
      containers:
      - name: zeek-live-container
        image: ghcr.io/idaholab/malcolm/zeek:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: common-upload-env
          - configMapRef:
              name: zeek-env
          - configMapRef:
              name: zeek-live-env
          - configMapRef:
              name: pcap-capture-env
        env:
          - name: ZEEK_LIVE_DISABLED
            value: "true"
