---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suricata-live-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: suricata-live-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: suricata-live-deployment
    spec:
      containers:
      - name: suricata-live-container
        image: ghcr.io/idaholab/malcolm/suricata:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: common-upload-env
          - configMapRef:
              name: suricata-env
          - configMapRef:
              name: suricata-live-env
          - configMapRef:
              name: pcap-capture-env
        env:
          - name: SURICATA_DISABLED
            value: "true"
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: var-local-catrust-volume
      volumes:
        - name: var-local-catrust-volume
          configMap:
            name: var-local-catrust
