---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: malcolm
spec:
  ports:
    - port: 443
      protocol: TCP
  selector:
    name: nginx-proxy-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: nginx-proxy-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx-proxy-deployment
    spec:
      containers:
      - name: nginx-proxy-container
        image: ghcr.io/idaholab/malcolm/nginx-proxy:kubernetes
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - containerPort: 443
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: auth-env
          - configMapRef:
              name: nginx-env
        livenessProbe:
          exec:
            command:
            - curl
            - --insecure
            - --silent
            - https://localhost:443
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: nginx-etc-nginx-volume
          mountPath: /etc/nginx/configmap
        - name: nginx-var-local-catrust-volume
          mountPath: /var/local/ca-trust/configmap
        - name: nginx-etc-nginx-certs-volume
          mountPath: /etc/nginx/certs/configmap
        - name: nginx-etc-nginx-certs-pem-volume
          mountPath: /etc/nginx/dhparam/configmap
        - name: nginx-opensearch-curlrc-volume
          mountPath: /var/local/curlrc/configmap
      volumes:
      - name: nginx-etc-nginx-volume
        configMap:
          name: etc-nginx
      - name: nginx-var-local-catrust-volume
        configMap:
          name: var-local-catrust
      - name: nginx-etc-nginx-certs-volume
        configMap:
          name: etc-nginx-certs
      - name: nginx-etc-nginx-certs-pem-volume
        configMap:
          name: etc-nginx-certs-pem
      - name: nginx-opensearch-curlrc-volume
        configMap:
          name: opensearch-curlrc
