version = 1

[[steps]]
[steps.shell]
script = '''
echo "Configuring \"$HOME\" environment"
touch "$HOME"/.hushlogin
echo "set nocompatible" > "$HOME"/.vimrc
mkdir -p "$HOME"/.local/bin "$HOME"/.config
DOTFILES_GITHUB_PATH="$HOME"/.config/dotfiles

git clone --depth=1 --recurse-submodules --shallow-submodules --single-branch \
  https://github.com/mmguero/dotfiles "$DOTFILES_GITHUB_PATH"

[[ -r "$DOTFILES_GITHUB_PATH"/bash/development_setup.sh ]] && rm -vf "$HOME"/.local/bin/development_setup.sh && \
  ln -vrs "$DOTFILES_GITHUB_PATH"/bash/development_setup.sh "$HOME"/.local/bin/development_setup.sh

[[ -r "$DOTFILES_GITHUB_PATH"/bash/rc ]] && rm -vf "$HOME"/.bashrc && \
  ln -vrs "$DOTFILES_GITHUB_PATH"/bash/rc "$HOME"/.bashrc

[[ -r "$DOTFILES_GITHUB_PATH"/bash/aliases ]] && rm -vf "$HOME"/.bash_aliases && \
  ln -vrs "$DOTFILES_GITHUB_PATH"/bash/aliases "$HOME"/.bash_aliases

[[ -r "$DOTFILES_GITHUB_PATH"/bash/functions ]] && rm -vf "$HOME"/.bash_functions && \
  ln -vrs "$DOTFILES_GITHUB_PATH"/bash/functions "$HOME"/.bash_functions

[[ -d "$DOTFILES_GITHUB_PATH"/bash/rc.d ]] && rm -vf "$HOME"/.bashrc.d && \
  ln -vrs "$DOTFILES_GITHUB_PATH"/bash/rc.d "$HOME"/.bashrc.d

[[ -r "$DOTFILES_GITHUB_PATH"/git/gitconfig ]] && rm -vf "$HOME"/.gitconfig && \
  ln -vrs "$DOTFILES_GITHUB_PATH"/git/gitconfig "$HOME"/.gitconfig

[[ -r "$DOTFILES_GITHUB_PATH"/git/gitignore_global ]] && rm -vf "$HOME"/.gitignore_global && \
  ln -vrs "$DOTFILES_GITHUB_PATH"/git/gitignore_global "$HOME"/.gitignore_global

[[ -r "$DOTFILES_GITHUB_PATH"/linux/tmux/tmux.conf ]] && rm -vf "$HOME"/.tmux.conf && \
  ln -vrs "$DOTFILES_GITHUB_PATH"/linux/tmux/tmux.conf "$HOME"/.tmux.conf

[[ -r "$DOTFILES_GITHUB_PATH"/starship/starship.toml ]] && rm -vf "$HOME"/.config/starship.toml && \
  ln -vrs "$DOTFILES_GITHUB_PATH"/starship/starship.toml "$HOME"/.config/starship.toml

LINKED_SCRIPTS=(
  self_signed_key_gen.sh
)
for i in ${LINKED_SCRIPTS[@]}; do
  rm -vf "$HOME"/.local/bin/"$i" && ln -vrs "$DOTFILES_GITHUB_PATH"/scripts/"$i" "$HOME"/.local/bin/
done

[[ -r "$DOTFILES_GITHUB_PATH"/bash/context-color/context-color ]] && rm -vf "$HOME"/.local/bin/context-color && \
  ln -vrs "$DOTFILES_GITHUB_PATH"/bash/context-color/context-color "$HOME"/.local/bin/context-color
'''
