name: malcolm-iso-build-docker-wrap-push-ghcr

on:
  push:
    branches:
      - main
      - development
    paths:
      - 'malcolm-iso/**'
      - 'shared/bin/*'
      - '!shared/bin/configure-capture.py'
      - '!shared/bin/zeek*'
      - '.trigger_iso_workflow_build'
      - '.github/workflows/malcolm-iso-build-docker-wrap-push-ghcr.yml'
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      actions: write
      packages: write
      contents: read
      security-events: write
    defaults:
      run:
        shell: bash
    steps:
      -
        name: Cancel previous run in progress
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          ignore_sha: true
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:master
      -
        name: Build environment setup
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc || true
          dpkg --get-selections
          DEBIAN_PACKAGE_LIST=(
            ansible
            ant
            ant-optional
            apt-transport-https
            aria2
            azure-cli
            bazel
            cabal-install-2.0
            cabal-install-2.2
            cabal-install-2.4
            cabal-install-3.0
            cabal-install-3.2
            chrpath
            clang-6.0
            clang-8
            clang-9
            clang-format-6.0
            clang-format-8
            clang-format-9
            clangd-9
            dotnet-sdk-3.0
            dotnet-sdk-3.1=3.1.101-1
            esl-erlang
            firefox
            g++-8
            g++-9
            gfortran-8
            gfortran-9
            ghc-8.0.2
            ghc-8.10.1
            ghc-8.2.2
            ghc-8.4.4
            ghc-8.6.2
            ghc-8.6.3
            ghc-8.6.4
            ghc-8.6.5
            ghc-8.8.1
            ghc-8.8.2
            ghc-8.8.3
            google-chrome-stable
            google-cloud-sdk
            heroku
            imagemagick
            kubectl
            libfontconfig1
            libfontconfig1-dev
            libfreetype6
            libfreetype6-dev
            libmagic-dev
            libmagickcore-dev
            libmagickwand-dev
            libmysqlclient-dev
            libpq-dev
            libssl-dev
            libxft-dev
            lld-6.0
            lld-8
            lld-9
            lldb-6.0
            lldb-8
            lldb-9
            mercurial
            mongodb-org
            mono-complete
            mssql-tools
            mysql-client
            mysql-server
            php-amqp
            php-apcu
            php-igbinary
            php-memcache
            php-memcached
            php-mongodb
            php-redis
            php-xdebug
            php-zmq
            php7.1
            php7.1-bcmath
            php7.1-bz2
            php7.1-cgi
            php7.1-cli
            php7.1-common
            php7.1-curl
            php7.1-dba
            php7.1-dev
            php7.1-enchant
            php7.1-fpm
            php7.1-gd
            php7.1-gmp
            php7.1-imap
            php7.1-interbase
            php7.1-intl
            php7.1-json
            php7.1-ldap
            php7.1-mbstring
            php7.1-mcrypt
            php7.1-mysql
            php7.1-odbc
            php7.1-opcache
            php7.1-pgsql
            php7.1-phpdbg
            php7.1-pspell
            php7.1-readline
            php7.1-recode
            php7.1-snmp
            php7.1-soap
            php7.1-sqlite3
            php7.1-sybase
            php7.1-tidy
            php7.1-xml
            php7.1-xmlrpc
            php7.1-xsl
            php7.1-zip
            php7.2
            php7.2-bcmath
            php7.2-bz2
            php7.2-cgi
            php7.2-cli
            php7.2-common
            php7.2-curl
            php7.2-dba
            php7.2-dev
            php7.2-enchant
            php7.2-fpm
            php7.2-gd
            php7.2-gmp
            php7.2-imap
            php7.2-interbase
            php7.2-intl
            php7.2-json
            php7.2-ldap
            php7.2-mbstring
            php7.2-mysql
            php7.2-odbc
            php7.2-opcache
            php7.2-pgsql
            php7.2-phpdbg
            php7.2-pspell
            php7.2-readline
            php7.2-recode
            php7.2-snmp
            php7.2-soap
            php7.2-sqlite3
            php7.2-sybase
            php7.2-tidy
            php7.2-xml
            php7.2-xmlrpc
            php7.2-xsl
            php7.2-zip
            php7.3
            php7.3-bcmath
            php7.3-bz2
            php7.3-cgi
            php7.3-cli
            php7.3-common
            php7.3-curl
            php7.3-dba
            php7.3-dev
            php7.3-enchant
            php7.3-fpm
            php7.3-gd
            php7.3-gmp
            php7.3-imap
            php7.3-interbase
            php7.3-intl
            php7.3-json
            php7.3-ldap
            php7.3-mbstring
            php7.3-mysql
            php7.3-odbc
            php7.3-opcache
            php7.3-pgsql
            php7.3-phpdbg
            php7.3-pspell
            php7.3-readline
            php7.3-recode
            php7.3-snmp
            php7.3-soap
            php7.3-sqlite3
            php7.3-sybase
            php7.3-tidy
            php7.3-xml
            php7.3-xmlrpc
            php7.3-xsl
            php7.3-zip
            php7.4
            php7.4-bcmath
            php7.4-bz2
            php7.4-cgi
            php7.4-cli
            php7.4-common
            php7.4-curl
            php7.4-dba
            php7.4-dev
            php7.4-enchant
            php7.4-fpm
            php7.4-gd
            php7.4-gmp
            php7.4-imap
            php7.4-interbase
            php7.4-intl
            php7.4-json
            php7.4-ldap
            php7.4-mbstring
            php7.4-mysql
            php7.4-odbc
            php7.4-opcache
            php7.4-pgsql
            php7.4-phpdbg
            php7.4-pspell
            php7.4-readline
            php7.4-snmp
            php7.4-soap
            php7.4-sqlite3
            php7.4-sybase
            php7.4-tidy
            php7.4-xml
            php7.4-xmlrpc
            php7.4-xsl
            php7.4-zip
            pollinate
            postgresql-client
            powershell
            rpm
            ruby-full
            shellcheck
            snmp
            sphinxsearch
            subversion
            unixodbc-dev
            yarn
            zsync
          )
          for i in ${DEBIAN_PACKAGE_LIST[@]}; do
            sudo env DEBIAN_FRONTEND=noninteractive apt-get -yq --purge remove "$i" >/dev/null 2>&1 || true
          done
          sudo env DEBIAN_FRONTEND=noninteractive apt-get autoremove -y >/dev/null 2>&1 || true
          sudo env DEBIAN_FRONTEND=noninteractive apt-get autoclean -y >/dev/null 2>&1 || true
          sudo env DEBIAN_FRONTEND=noninteractive apt-get -q update
          sudo env DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y -q \
               apt-transport-https \
               bc \
               build-essential \
               ca-certificates \
               curl \
               debhelper-compat \
               debian-archive-keyring \
               debootstrap \
               genisoimage \
               gettext \
               git \
               gnupg2 \
               imagemagick \
               jq \
               po4a \
               rsync \
               software-properties-common \
               squashfs-tools \
               virt-what \
               xorriso \
               xz-utils
          df -h
          git clone --depth=1 --single-branch --recurse-submodules --shallow-submodules --branch='debian/1%20210407' 'https://salsa.debian.org/live-team/live-build.git' /tmp/live-build
          cd /tmp/live-build
          dpkg-buildpackage -b -uc -us
          cd /tmp
          sudo dpkg -i /tmp/live-build*.deb
          rm -rf /tmp/live-build
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: extract_branch
      -
        name: Extract commit SHA
        shell: bash
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        id: extract_commit_sha
      -
        name: Extract Malcolm version
        shell: bash
        run: echo "mversion=$(grep -P "^\s+image:\s*malcolm" docker-compose.yml | awk '{print $2}' | cut -d':' -f2 | uniq -c | sort -nr | awk '{print $2}' | head -n 1)" >> $GITHUB_OUTPUT
        id: extract_malcolm_version
      -
        name: Build image
        run: |
          IMAGES=( $(grep image: docker-compose.yml | awk '{print $2}' | sort -u) )
          for IMAGE in "${IMAGES[@]}"; do
            REPO_IMAGE="$(echo "$IMAGE" | sed "s@^.*\(malcolm\)@ghcr.io/${{ github.repository_owner }}/\1@" | sed "s/:.*/:${{ steps.extract_branch.outputs.branch }}/")"
            docker pull "$REPO_IMAGE" && \
              docker tag "$REPO_IMAGE" "$IMAGE" && \
              docker rmi "$REPO_IMAGE"
          done
          DEST_IMAGES_TXZ=$(pwd)/malcolm_"$(date +%Y.%m.%d_%H:%M:%S)"_${{ steps.extract_commit_sha.outputs.sha }}_images.tar.xz
          echo "Saving Malcolm Docker images to \"$DEST_IMAGES_TXZ\""
          docker save "${IMAGES[@]}" | xz -1 > "$DEST_IMAGES_TXZ"
          for IMAGE in "${IMAGES[@]}"; do
            docker rmi "$IMAGE"
          done
          pushd ./malcolm-iso
          mkdir -p ./shared
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > ./shared/environment.chroot
          sudo /usr/bin/env bash ./build.sh -r -d "$DEST_IMAGES_TXZ"
          rm -rf ./shared/ "$DEST_IMAGES_TXZ"
          sudo chmod 644 ./malcolm-*.*
          popd
      -
        name: Run Trivy vulnerability scanner
        id: trivy-scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './malcolm-iso'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'
          vuln-type: 'os,library'
          hide-progress: true
          ignore-unfixed: true
          exit-code: '0'
      -
        name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
      -
        name: ghcr.io login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push ISO image
        uses: docker/build-push-action@v3
        with:
          context: ./malcolm-iso
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/malcolm/malcolm:${{ steps.extract_branch.outputs.branch }}
